version: '3.8'
services:
  tietokanta:
    image: mysql:latest
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./db.sql:/docker-entrypoint-initdb.d/1.sql"
